module.exports = {
    TOWER_LEFT  : '<',
    TOWER_RIGHT : '>',
    TOWER_UP    : '^',
    TOWER_DOWN  : 'v',
    SPACE       : ' ',
    TARGET      : '@',
    BLOCK       : '#',
    MIRROR_LEFT : '\\',
    MIRROR_RIGHT: '/',
    LEFT        : { x: -1, y: 0 },
    RIGHT       : { x: 1, y: 0 },
    UP          : { x: 0, y: -1 },
    DOWN        : { x: 0, y: 1 },
    PORTAL_0    : '0',
    PORTAL_1    : '1',
    PORTAL_2    : '2',
    PORTAL_3    : '3',
    PORTAL_4    : '4',
    PORTAL_5    : '5',
    PORTAL_6    : '6',
    PORTAL_7    : '7',
    PORTAL_8    : '8',
    PORTAL_9    : '9'
};